/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FileType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
export const Verdict = IDL.Variant({ 'fake' : IDL.Null, 'real' : IDL.Null });
export const Metric = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });
export const AnalysisRecord = IDL.Record({
  'id' : IDL.Nat,
  'fileType' : FileType,
  'verdict' : Verdict,
  'filename' : IDL.Text,
  'confidenceScore' : IDL.Nat,
  'timestamp' : IDL.Int,
  'analysisMetrics' : IDL.Vec(Metric),
});

export const idlService = IDL.Service({
  'createAnalysisRecord' : IDL.Func(
      [IDL.Text, FileType, Verdict, IDL.Nat, IDL.Vec(Metric)],
      [IDL.Nat],
      [],
    ),
  'deleteRecordById' : IDL.Func([IDL.Nat], [], []),
  'getAllRecords' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FileType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const Verdict = IDL.Variant({ 'fake' : IDL.Null, 'real' : IDL.Null });
  const Metric = IDL.Record({ 'name' : IDL.Text, 'score' : IDL.Nat });
  const AnalysisRecord = IDL.Record({
    'id' : IDL.Nat,
    'fileType' : FileType,
    'verdict' : Verdict,
    'filename' : IDL.Text,
    'confidenceScore' : IDL.Nat,
    'timestamp' : IDL.Int,
    'analysisMetrics' : IDL.Vec(Metric),
  });
  
  return IDL.Service({
    'createAnalysisRecord' : IDL.Func(
        [IDL.Text, FileType, Verdict, IDL.Nat, IDL.Vec(Metric)],
        [IDL.Nat],
        [],
      ),
    'deleteRecordById' : IDL.Func([IDL.Nat], [], []),
    'getAllRecords' : IDL.Func([], [IDL.Vec(AnalysisRecord)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };