/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisRecord {
  'id' : bigint,
  'fileType' : FileType,
  'verdict' : Verdict,
  'filename' : string,
  'confidenceScore' : bigint,
  'timestamp' : bigint,
  'analysisMetrics' : Array<Metric>,
}
export type FileType = { 'video' : null } |
  { 'image' : null };
export interface Metric { 'name' : string, 'score' : bigint }
export type Verdict = { 'fake' : null } |
  { 'real' : null };
export interface _SERVICE {
  'createAnalysisRecord' : ActorMethod<
    [string, FileType, Verdict, bigint, Array<Metric>],
    bigint
  >,
  'deleteRecordById' : ActorMethod<[bigint], undefined>,
  'getAllRecords' : ActorMethod<[], Array<AnalysisRecord>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];