/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Metric {
    name: string;
    score: bigint;
}
export interface AnalysisRecord {
    id: bigint;
    fileType: FileType;
    verdict: Verdict;
    filename: string;
    confidenceScore: bigint;
    timestamp: bigint;
    analysisMetrics: Array<Metric>;
}
export enum FileType {
    video = "video",
    image = "image"
}
export enum Verdict {
    fake = "fake",
    real = "real"
}
export interface backendInterface {
    createAnalysisRecord(filename: string, fileType: FileType, verdict: Verdict, confidenceScore: bigint, metrics: Array<Metric>): Promise<bigint>;
    deleteRecordById(id: bigint): Promise<void>;
    getAllRecords(): Promise<Array<AnalysisRecord>>;
}
import type { AnalysisRecord as _AnalysisRecord, FileType as _FileType, Metric as _Metric, Verdict as _Verdict } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createAnalysisRecord(arg0: string, arg1: FileType, arg2: Verdict, arg3: bigint, arg4: Array<Metric>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createAnalysisRecord(arg0, to_candid_FileType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_Verdict_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAnalysisRecord(arg0, to_candid_FileType_n1(this._uploadFile, this._downloadFile, arg1), to_candid_Verdict_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async deleteRecordById(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecordById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecordById(arg0);
            return result;
        }
    }
    async getAllRecords(): Promise<Array<AnalysisRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecords();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecords();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AnalysisRecord_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnalysisRecord): AnalysisRecord {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_FileType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Verdict_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Verdict): Verdict {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    fileType: _FileType;
    verdict: _Verdict;
    filename: string;
    confidenceScore: bigint;
    timestamp: bigint;
    analysisMetrics: Array<_Metric>;
}): {
    id: bigint;
    fileType: FileType;
    verdict: Verdict;
    filename: string;
    confidenceScore: bigint;
    timestamp: bigint;
    analysisMetrics: Array<Metric>;
} {
    return {
        id: value.id,
        fileType: from_candid_FileType_n8(_uploadFile, _downloadFile, value.fileType),
        verdict: from_candid_Verdict_n10(_uploadFile, _downloadFile, value.verdict),
        filename: value.filename,
        confidenceScore: value.confidenceScore,
        timestamp: value.timestamp,
        analysisMetrics: value.analysisMetrics
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fake: null;
} | {
    real: null;
}): Verdict {
    return "fake" in value ? Verdict.fake : "real" in value ? Verdict.real : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): FileType {
    return "video" in value ? FileType.video : "image" in value ? FileType.image : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnalysisRecord>): Array<AnalysisRecord> {
    return value.map((x)=>from_candid_AnalysisRecord_n6(_uploadFile, _downloadFile, x));
}
function to_candid_FileType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Verdict_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Verdict): _Verdict {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    video: null;
} | {
    image: null;
} {
    return value == FileType.video ? {
        video: null
    } : value == FileType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Verdict): {
    fake: null;
} | {
    real: null;
} {
    return value == Verdict.fake ? {
        fake: null
    } : value == Verdict.real ? {
        real: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
